### ISSUE TITLE
Support for post-commit hook

### ISSUE THREAD

**Issue by f0086** [y0ung3r/GitGlobalHooksLocator#23]
Is there a reason why the plugin does not support the ```post-commit``` hook?

**Comment by y0ung3r** [comment]
Hello, Aaron!

Can you tell me a little more about this problem?

The `post-commit` is working fine for me:
![image](https://github.com/y0ung3r/GitGlobalHooksLocator/assets/55300023/cc13a45c-9349-424b-ba19-951302705dd4)

Note: At this time, automatic updating of the disabled/enabled hooks list is not supported. To make a new added hook appear in the list, you need to reload the IDE. This is inconvenient, but I have already planned to implement this functionality for the next release.

**Comment by f0086** [comment]
My problem was not related to this plugin, I had a bug in the script itself + I had not reloaded the IDE. So, this issue can be keep closed :)

**Comment by y0ung3r** [comment]
Got it.

I hope you found this plugin useful. Thank you for using it!
